# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-01-02 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('song_name', models.CharField(max_length=255)),
                ('review_sentiment', models.CharField(max_length=255)),
            ],
        ),
    ]
