# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-01-12 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0003_auto_20230112_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommends',
            new_name='Recommend',
        ),
    ]
