# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-01-12 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0004_auto_20230112_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='review',
            field=models.TextField(),
        ),
    ]
